package com.reactivecommerce.notification.domain.model;

public enum NotificationType {
    ORDER_CREATED, ORDER_COMPLETED, ORDER_FAILED, ORDER_REFUNDED,
    ASSET_UPLOADED, ASSET_APPROVED, ASSET_REJECTED, ASSET_PUBLISHED,
    REVIEW_CREATED, DOWNLOAD_READY, REPORT_READY,
    USER_REGISTERED, WELCOME
}
