spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/reactive_commerce}
    username: ${SPRING_R2DBC_USERNAME:rcadmin}
    password: ${SPRING_R2DBC_PASSWORD:rcpassword}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:rcredis}

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

aws:
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY_ID:local}
  secret-key: ${AWS_SECRET_ACCESS_KEY:local}
  s3:
    bucket: ${AWS_S3_BUCKET:reactive-commerce-assets}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  bulkhead:
    instances:
      s3:
        maxConcurrentCalls: 10
  retry:
    instances:
      s3:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
